# Generated by Django 3.0 on 2022-11-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_infsourcetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='infsourcetag',
            name='infsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infsourcetag_package', to='base.Infsource'),
        ),
        migrations.AlterUniqueTogether(
            name='infsourcetag',
            unique_together={('key', 'value', 'infsource')},
        ),
    ]
